### ISSUE TITLE
Codes for Point Cloud Abstraction

### ISSUE THREAD

**Issue by Dustinpro** [daerduoCarey/structurenet#1]
As stated in section 6.4 of StructureNet paper, it trains another PointNet++-based encoder to encode point clouds, which shows the strength of latent space. Could you please provide codes and brief network design for this part (point cloud abstraction)? Thanks! @daerduoCarey

**Comment by daerduoCarey** [comment]
It's just a straight-forward PointNet++ to extract point cloud global features. Since we have the ground-truth PartNet data, we can directly regress the global feature to the learned StructureNet AE embedding. We pre-train and fix the StructureNet AE network. Then, for each shape in PartNet, we regress the PointNet++ global shape feature to the AE bottleneck feature.

**Comment by Dustinpro** [comment]
Thank you!
